root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/server -tags development ./cmd/proxy-server-go"
bin = "./tmp/server"
full_bin = ""
delay = 1000
include_dir = []
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_file = []
exclude_regex = ["_test.go"]
follow_symlink = true
log = "air.log"
stop_on_error = true
send_interrupt = false
kill_delay = 0

[log]
time = false

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true
