version: "3.8"

services:
  # proxy
  proxy-server:
    container_name: proxy-server
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    ports:
      - 8888:8888
    volumes:
      - .:/proxy-server
      - /var/run/docker.sock:/var/run/docker.sock
    tty: true
    environment:
      - ENV=development
    networks:
      - proxy-server-go-network

  # redis
  redis:
    container_name: proxy-server-go-redis
    build:
      context: ./docker/redis
      dockerfile: Dockerfile
    ports:
      - 6379:6379
    volumes:
      - ./docker/redis/data:/data
    tty: true
    restart: always
    environment:
      - TZ=Asia/Tokyo
    networks:
      - proxy-server-go-network

networks:
  proxy-server-go-network:
    driver: bridge
