version: "3.8"

services:
  redis:
    container_name: redis-cluster-study-redis
    build:
      context: .
      dockerfile: ./docker/redis/Dockerfile
    ports:
      - 6379:6379
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/data:/data
    tty: true
    networks:
      - redis-cluster-networks
  postgres:
    container_name: redis-cluster-study-postgres
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    tty: true
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ=Asia/Tokyo
    networks:
      - redis-cluster-networks

networks:
  redis-cluster-networks:
    driver: bridge
