name: packages
on: pull_request

jobs:
  check-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Golang
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.4"
      - name: Run go mod tidy
        run: |
          go mod tidy
          git diff --exit-code
